export type ThemeMode = 'light' | 'dark';

export interface ThemePalette {
  bgApp: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  border: string;
  borderLight: string;
  title: string;
  accent: string;
  badgeLiveBg: string;
  badgeLiveColor: string;
  badgeLiveBorder: string;
  dotLive: string;
  divider: string;
  poolNoticeBg: string;
  poolNoticeColor: string;
  poolWrapperBg: string;
  poolWrapperBorder: string;
  poolWrapperShadow: string;
  cardBg: string;
  cardBorder: string;
  cardShadow: string;
  squadCompleteBg: string;
  squadCompleteColor: string;
  squadCompleteBorder: string;
  squadIncompleteBg: string;
  squadIncompleteColor: string;
  squadIncompleteBorder: string;
  metricPurseText: string;
  metricPurseBg: string;
  metricSpentText: string;
  metricSpentBg: string;
  metricGoodText: string;
  metricGoodBg: string;
  metricBadText: string;
  metricBadBg: string;
  tableHeaderBg: string;
  thColor: string;
  thBorder: string;
  trEven: string;
  trOdd: string;
  trBorder: string;
  tdColor: string;
  tdNameColor: string;
  tdPriceColor: string;
  emptyBg: string;
  emptyBorder: string;
  emptyColor: string;
  poolBadgeBg: string;
  poolBadgeColor: string;
  poolBadgeBorder: string;
  loadingColor: string;
  errorBg: string;
  errorColor: string;
  errorBorder: string;
  errorSubtext: string;
  toggleBg: string;
  toggleBorder: string;
  toggleColor: string;
  toggleHoverBg: string;
}

export const lightPalette: ThemePalette = {
  bgApp: '#f8fafc',
  textPrimary: '#0f172a',
  textSecondary: '#4b5563',
  textMuted: '#9ca3af',
  border: '#e5e7eb',
  borderLight: '#e2e8f0',
  title: '#1e3a8a',
  accent: '#3b82f6',
  badgeLiveBg: '#fee2e2',
  badgeLiveColor: '#ef4444',
  badgeLiveBorder: '#fca5a5',
  dotLive: '#ef4444',
  divider: '#e2e8f0',
  poolNoticeBg: '#e0f2fe',
  poolNoticeColor: '#0369a1',
  poolWrapperBg: '#ffffff',
  poolWrapperBorder: '#e2e8f0',
  poolWrapperShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.02)',
  cardBg: '#ffffff',
  cardBorder: '#e5e7eb',
  cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
  squadCompleteBg: '#d1fae5',
  squadCompleteColor: '#065f46',
  squadCompleteBorder: '#a7f3d0',
  squadIncompleteBg: '#f3f4f6',
  squadIncompleteColor: '#374151',
  squadIncompleteBorder: '#e5e7eb',
  metricPurseText: '#1e3a8a',
  metricPurseBg: '#dbeafe',
  metricSpentText: '#4b5563',
  metricSpentBg: '#f3f4f6',
  metricGoodText: '#047857',
  metricGoodBg: '#d1fae5',
  metricBadText: '#b91c1c',
  metricBadBg: '#fee2e2',
  tableHeaderBg: '#f9fafb',
  thColor: '#4b5563',
  thBorder: '#e5e7eb',
  trEven: '#ffffff',
  trOdd: '#f9fafb',
  trBorder: '#f3f4f6',
  tdColor: '#4b5563',
  tdNameColor: '#111827',
  tdPriceColor: '#2563eb',
  emptyBg: '#f9fafb',
  emptyBorder: '#e5e7eb',
  emptyColor: '#9ca3af',
  poolBadgeBg: '#f1f5f9',
  poolBadgeColor: '#475569',
  poolBadgeBorder: '#e2e8f0',
  loadingColor: '#4b5563',
  errorBg: '#fef2f2',
  errorColor: '#dc2626',
  errorBorder: '#fee2e2',
  errorSubtext: '#991b1b',
  toggleBg: '#ffffff',
  toggleBorder: '#e2e8f0',
  toggleColor: '#0f172a',
  toggleHoverBg: '#f1f5f9',
};

export const darkPalette: ThemePalette = {
  bgApp: '#0f172a',
  textPrimary: '#f1f5f9',
  textSecondary: '#94a3b8',
  textMuted: '#64748b',
  border: '#334155',
  borderLight: '#1e293b',
  title: '#93c5fd',
  accent: '#60a5fa',
  badgeLiveBg: '#450a0a',
  badgeLiveColor: '#f87171',
  badgeLiveBorder: '#7f1d1d',
  dotLive: '#f87171',
  divider: '#334155',
  poolNoticeBg: '#0c4a6e',
  poolNoticeColor: '#7dd3fc',
  poolWrapperBg: '#1e293b',
  poolWrapperBorder: '#334155',
  poolWrapperShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
  cardBg: '#1e293b',
  cardBorder: '#334155',
  cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.25), 0 2px 4px -1px rgba(0, 0, 0, 0.15)',
  squadCompleteBg: '#064e3b',
  squadCompleteColor: '#6ee7b7',
  squadCompleteBorder: '#047857',
  squadIncompleteBg: '#334155',
  squadIncompleteColor: '#cbd5e1',
  squadIncompleteBorder: '#475569',
  metricPurseText: '#93c5fd',
  metricPurseBg: '#1e3a5f',
  metricSpentText: '#cbd5e1',
  metricSpentBg: '#334155',
  metricGoodText: '#6ee7b7',
  metricGoodBg: '#064e3b',
  metricBadText: '#fca5a5',
  metricBadBg: '#450a0a',
  tableHeaderBg: '#0f172a',
  thColor: '#94a3b8',
  thBorder: '#334155',
  trEven: '#1e293b',
  trOdd: '#172033',
  trBorder: '#334155',
  tdColor: '#94a3b8',
  tdNameColor: '#f1f5f9',
  tdPriceColor: '#60a5fa',
  emptyBg: '#0f172a',
  emptyBorder: '#334155',
  emptyColor: '#64748b',
  poolBadgeBg: '#334155',
  poolBadgeColor: '#cbd5e1',
  poolBadgeBorder: '#475569',
  loadingColor: '#94a3b8',
  errorBg: '#450a0a',
  errorColor: '#fca5a5',
  errorBorder: '#7f1d1d',
  errorSubtext: '#fecaca',
  toggleBg: '#1e293b',
  toggleBorder: '#334155',
  toggleColor: '#f1f5f9',
  toggleHoverBg: '#334155',
};

export const palettes: Record<ThemeMode, ThemePalette> = {
  light: lightPalette,
  dark: darkPalette,
};
